[pytest]
markers =
    ui: mark a test as a UI test.
    api: mark a test as an API test.
    logic: mark a test as a business logic unit test.
addopts = -v -s --alluredir=reports/allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
